apiVersion: v1
kind: Service
metadata:
  name: diagnostic-service
  namespace: it-diagnostics
spec:
  type: ClusterIP
  ports:
  - port: 5002
    targetPort: 5002
  selector:
    app: diagnostic-service
