apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: it-diagnostics
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30004  # Hardcoded NodePort
  selector:
    app: frontend
